# Sample workflow for building and deploying a mdBook site to GitHub Pages
#
# To get started with mdBook see: https://rust-lang.github.io/mdBook/index.html
#
name: Check MDBook build

on:
  # Runs on pushes targeting the default branch
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Install mdBook
        uses: taiki-e/install-action@v2
        with:
          tool: mdbook@0.4.49
      - name: Install mdBook mermaid
        uses: taiki-e/install-action@v2
        with:
          tool: mdbook-mermaid@0.15.0
      - name: Install mdBook katex
        uses: taiki-e/install-action@v2
        with:
          tool: mdbook-katex@0.9.4
      - name: Install mdBook linkcheck
        uses: taiki-e/install-action@v2
        with:
          tool: mdbook-linkcheck@0.7.7
      - name: Install mdBook llms-txt
        uses: taiki-e/install-action@v2
        with:
          tool: mdbook-llms-txt@0.1.1
      - name: Build with mdBook
        run: mdbook build
      - name: Fix the llms.txt location
        run: |
          mv book/llms-txt/llms.txt book/html/llms.txt
          mv book/llms-txt-full/llms-full.txt book/html/llms-full.txt